name: Deploy Site

on:
  push:
    branches: ["master"]

jobs:
  build-and-deply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Deps
        run: npm install --production

      - name: Build Static Site
        run: |
          npm run build

      - name: Deploy Static Site
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avz --delete
          path: out/
          remote_path: /apps/personal-website
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.HOST_USER }}
          remote_key: ${{ secrets.HOST_SSH_KEY }}

  
